x1 = int(input('Введите x1: '))
y1 = int(input('Введите y1: '))
x2 = int(input('Введите x2: '))
y2 = int(input('Введите y2: '))
dist = round(((x1 - x2)**2 + (y1 - y2)**2)**0.5, 3)
print('Расстояние между двумя точками равно', dist)